//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class baitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public baitap()
        {
            this.kiluc = new HashSet<kiluc>();
        }
    
        public string mabaitap { get; set; }
        public string tenbaitap { get; set; }
        public string noidung { get; set; }
        public string dokho { get; set; }
        public Nullable<System.TimeSpan> thoigian { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<double> diemmokhoa { get; set; }
        public bool Xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kiluc> kiluc { get; set; }
    }
}
