//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemdanh
    {
        public string manguoidung { get; set; }
        public System.DateTime ngay { get; set; }
    
        public virtual nguoidung nguoidung { get; set; }
    }
}
