//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiluc
    {
        public string makiluc { get; set; }
        public string manguoidung { get; set; }
        public string mabaitap { get; set; }
        public Nullable<double> diembaitap { get; set; }
        public Nullable<int> solanthuchien { get; set; }
    
        public virtual baitap baitap { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
