//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Typing_Practice_DBEntities : DbContext
    {
        public Typing_Practice_DBEntities()
            : base("name=Typing_Practice_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<baitap> baitaps { get; set; }
        public virtual DbSet<diemdanh> diemdanhs { get; set; }
        public virtual DbSet<kiluc> kilucs { get; set; }
        public virtual DbSet<nguoidung> nguoidungs { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
    }
}
